name: Docs

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  docs:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Make docs
      run: cargo doc --verbose --no-deps
    - name: Add index.html stub
      run: echo "<meta http-equiv=refresh content=0;url=giga/index.html>" > ./target/doc/index.html
    - name: Deploy docs
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target/doc
